"""

Revision ID: 47b2fd2fbbe0
Revises: e3c1310b3a04
Create Date: 2026-08-22 20:58:34.798056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b2fd2fbbe0'
down_revision: Union[str, Sequence[str], None] = 'e3c1310b3a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tasks_celery_task_id'), 'tasks', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_celery_task_id'), table_name='tasks')
    op.drop_column('tasks', 'celery_task_id')
    # ### end Alembic commands ###
