"""

Revision ID: a26779b60c2f
Revises: 240d24f7087a
Create Date: 2026-08-10 10:38:34.239381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26779b60c2f'
down_revision: Union[str, Sequence[str], None] = '240d24f7087a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tasks', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
