"""

Revision ID: b54bba93ce54
Revises: 47b2fd2fbbe0
Create Date: 2026-08-23 14:42:00.597928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54bba93ce54'
down_revision: Union[str, Sequence[str], None] = '47b2fd2fbbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_celery_task_id'), table_name='tasks')
    op.drop_column('tasks', 'celery_task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('celery_task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_tasks_celery_task_id'), 'tasks', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###
